version: "3.8"
services:
  mariadb:
    image: mariadb:10.9.3
    ports:
      - 3306:3306
    # expose:
    # - "3306"
    # volumes:
    #   - ~/apps/mariadb:/var/lib/mysql
    env_file:
      - .env

  adminer:
      image: adminer:latest
      #restart: always
      ports:
      - 9999:8080


  api:
      image: api:latest
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - .env
      ports:
        - 5000:5000
      depends_on:
        - mariadb
   